### ISSUE TITLE
False positive for keyword "fn"

### ISSUE THREAD

**Issue by Sogomn** [zargony/atom-language-rust#103]
![bug2](https://cloud.githubusercontent.com/assets/13470340/23945715/d9280e54-0977-11e7-8f28-34f1e14a7bbe.png)

**Comment by KalitaAlexey** [comment]
It was fixed in https://github.com/zargony/atom-language-rust/pull/99

@zargony,
I suppose you should publish a new version.

**Comment by Sogomn** [comment]
Okay, sorry, couldn't find it.
