### ISSUE TITLE
Breaks global editor.tab-length

### ISSUE THREAD

**Issue by alexbuzzbee** [zargony/atom-language-rust#108]
This package breaks the global setting for `editor.tab-length`. It overrides the setting to `4`, but it is impossible to set it locally in the Atom `settings-view` to the global value, due to an assumption by `settings-view` that anything set to the global default should be discarded. This makes it impossible, should you have a preferred tab length beside `4`, to set the tab length used in Rust files to your global setting (without modifying the `rust.cson` file in the package source). Any other value can be used, but not the global value.

**Comment by zargony** [comment]
There's some talk about this in #93 as well. To me, this sounds like a bug in Atom (settings pages ignore package-level defaults). A known workaround is to add these settings manually to your `config.cson` until it gets fixed in Atom.
