### ISSUE TITLE
Angle brackets not being underlined for matching

### ISSUE THREAD

**Issue by Nokel81** [zargony/atom-language-rust#111]
With round brackets:
![capture1](https://user-images.githubusercontent.com/8225332/27603848-7f032f10-5b45-11e7-9291-e6e1bce581cb.PNG)

With angle brackets:
![capture2](https://user-images.githubusercontent.com/8225332/27603853-835cdec6-5b45-11e7-9504-e5337cecd156.PNG)

**Comment by zargony** [comment]
Which version of language-rust do you use? This should have been fixed in master a few hours ago.

**Comment by Nokel81** [comment]
Ah, that must be the problem since I have not yet updated
