### ISSUE TITLE
Support new integer type shorthand

### ISSUE THREAD

**Issue by gingermusketeer** [zargony/atom-language-rust#15]
Rust has recently changed the integer type shorthand
e.g
`10i => 10is`
`10u => 10us`

See https://github.com/rust-lang/rfcs/pull/544#issuecomment-68760871

**Comment by HeroesGrave** [comment]
Similarly, `usize` and `isize` aren't highlighted correctly either.

**Comment by zargony** [comment]
I just pushed a version where uint and int are updated to usize and isize

**Comment by zargony** [comment]
Oops, almost forgot the literal suffixes. Added them too

**Comment by gingermusketeer** [comment]
awesome thanks
