### ISSUE TITLE
Deprecated usage of 'editor' class

### ISSUE THREAD

**Issue by nixxquality** [zargony/atom-language-rust#16]
(from Deprecation Cop)
[stylesheets\rust.less](https://github.com/zargony/atom-language-rust/blob/master/stylesheets/rust.less)
Use the `atom-text-editor` tag instead of the `editor` class.
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by zargony** [comment]
Thanks. (I almost forgot the stylesheet) ;)
