### ISSUE TITLE
please publish to npm

### ISSUE THREAD

**Issue by bcoe** [zargony/atom-language-rust#17]
Could you please publish the rust module to npm? We are using the same highlighting engine as Atom now, and would love to add your grammar:

https://www.npmjs.com/package/polyglot-readme

**Comment by zargony** [comment]
I'm not very familiar with npm packages, but if it comes down to just adding a package description for npm, that would be no problem. I'm just unsure how it fits into the npm package world. What do you suggest?

**Comment by bcoe** [comment]
@zargony the package.json you're using for `apm` works great for `npm, you should be able to simply run:

```bash
cd atom-language-rust
npm login
npm publish
```

**Comment by zargony** [comment]
Done, thanks!
