### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by ruabmbua** [zargony/atom-language-rust#24]
Store package style sheets in the  styles/  directory instead of  stylesheets/  in the  language-rust  package     Package.getStylesheetsPath  c: Users Roland AppData Local atom app-0.189.0 resources app src package.js:448:9  Package.getStylesheetPaths  c: Users Roland AppData Local atom app-0.189.0 resources app src package.js:459:32

**Comment by zargony** [comment]
Thanks for reporting. This should be fixed with #23.

**Comment by alexchandel** [comment]
This wasn't fixed in 0.4.3 AFAIK. I'm still seeing both deprecation cop warnings.
