### ISSUE TITLE
Add '_' character to 'Non Word Characters' list

### ISSUE THREAD

**Issue by mcanders** [zargony/atom-language-rust#26]
I often want to select a part of a variable name.  Consider the variable name "line_index" with the cursor right before the 'l' ([cursor]line_index).  In order to select "line", I currently need to move to the end of "line" (either by hitting the "right arrow" key four times or clicking it with the mouse *shudders*) and hit control+shift+left to select to the beginning of the word.  Adding '_' to the 'Non Word Characters' list in the package settings allows me to select "line" by hitting ctrl+shift+right.  This emulates Sublime Text's alt+shift+right behavior.

**Comment by zargony** [comment]
I'm not sure if this would be a good idea. Most people probably expect underscores to be part of a word so that you can double-click or ctrl-shift-w on a variable or function name to select it. I'd vote for not adding '_' to the non word characters list.

**Comment by zargony** [comment]
I'm closing this since nobody else seems to be interested in changing this. I'm taking that as a sign that the current behavior is fine ;)
