### ISSUE TITLE
Raw string literals are not highlighted correctly

### ISSUE THREAD

**Issue by LaylConway** [zargony/atom-language-rust#27]
Example:

```rust
let value = r#" "
"#;
```

Anything after this is now considered inside a string.
This will work fine however:

```rust
let value = r#" " "#;
```

**Comment by LaylConway** [comment]
I think all this needs to be fixed is to allow newlines in the following regex.
https://github.com/zargony/atom-language-rust/blob/master/grammars/rust.cson#L56

**Comment by zargony** [comment]
Thanks :)
