### ISSUE TITLE
Distinguish doc comments from code comments

### ISSUE THREAD

**Issue by jayrandez** [zargony/atom-language-rust#34]
Would anyone be interested in this if its possible? Doc comments begin with /// and are generally much longer.

I'm partial towards making doc comments lighter and collapsible. Although collapsible may be difficult as they are single-line comments.

**Comment by zargony** [comment]
I looked through the syntax rules today and found that they're already distinguished. You can highlight them differently in your stylesheet. It's just that most syntax themes probably don't have different visuals for doc and normal comments.

Doc comments do have the CSS class `documentation` additionally to `comment` (and `block` if it's a multiline comment)

Try this in your `styles.less`:
```css
atom-text-editor::shadow .comment.documentation {
    color: red;
}
```
