### ISSUE TITLE
== does not always highlight correctly

### ISSUE THREAD

**Issue by nathansizemore** [zargony/atom-language-rust#40]
Not sure what triggers it, but here is an example - 

<img width="374" alt="screen shot 2015-07-15 at 5 13 59 pm" src="https://cloud.githubusercontent.com/assets/3423825/8710086/0a7865aa-2b15-11e5-82be-c52dca66aa59.png">

**Comment by dwayne** [comment]
Hey @nathansizemore,

Can you tell me what syntax theme you are using? For example, if I use any of the syntax themes that comes with atom I am unable to reproduce the error.

![_syntax_highlight_in_rust](https://cloud.githubusercontent.com/assets/319231/9396264/9c10763e-4761-11e5-920e-b6346f0b4842.png)

**Comment by nathansizemore** [comment]
Flayland theme - https://atom.io/themes/flatland-dark

**Comment by dwayne** [comment]
Thanks. I tried it out and it works for me. Do you still experience the problem? If yes, then what's surrounding the code?

**Comment by nathansizemore** [comment]
~~~rust
/// Runs the passed function
pub fn run(&mut self, fp_wrapper: Arc<FpWrapper>,
    sockets: SocketList, socket: Socket, buffer: Vec<u8>) {

    if self.next_worker == self.w_threads.len() {
        self.next_worker = 0;
    }

    let _ = self.w_threads[self.next_worker].sender().send((
        fp_wrapper, sockets, socket, buffer
    ));
    self.next_worker += 1;
}
~~~

**Comment by dwayne** [comment]
I'm still unable to reproduce. Can you dig into the HTML and tell me what syntax rule is being used for the `=` that is highlighted incorrectly.

For e.g.

![keyword-operator-rust](https://cloud.githubusercontent.com/assets/319231/9405901/cd059004-47c9-11e5-9eb8-fd07f4830b0a.png)

Mine is recognized as an operator with the classes `keyword operator rust`.

Also, I'm running `atom 1.0.7` on `Ubuntu 14.04`.

**Comment by nathansizemore** [comment]
Ubuntu 15.04
Atom v1.0.7

![screenshot from 2015-08-24 17 39 21](https://cloud.githubusercontent.com/assets/3423825/9453351/d174b7ee-4a87-11e5-8c95-75b8701a1968.png)

**Comment by dwayne** [comment]
@nathansizemore Given the entire file, I'm now seeing the incorrect syntax highlighting. Will look into it further.

**Comment by dwayne** [comment]
A smaller example that causes the problem.

![bad_ _syntax_highlighting](https://cloud.githubusercontent.com/assets/319231/9456408/213d0dcc-4aa5-11e5-83be-83aca6884912.png)
