### ISSUE TITLE
Matching 'pointy brackets' should get underlined, like parens and curly brackets do

### ISSUE THREAD

**Issue by frewsxcv** [zargony/atom-language-rust#51]
It's common to see type signatures like: `Option<Box<Iterator<Item=u64>>>`. It'd be helpful when a cursor is higlighted over one `<` or `>` to match its matching 'pointy bracket' like `(`, `)`, `{`, and `}` do.

**Comment by zargony** [comment]
Highlighting and jumping to matching brackets should work now
