### ISSUE TITLE
Ligatures not displaying properly 

### ISSUE THREAD

**Issue by siganos** [zargony/atom-language-rust#61]
<img width="148" alt="example" src="https://cloud.githubusercontent.com/assets/4865368/11426045/4f148126-946a-11e5-8d44-670c406abf8d.png">

When using fonts that support ligatures, the rust grammar breaks them as seen in the figure above. The ligature appear correctly only in the comment section. If i select Plain Text, the ligatures appear correctly in both cases.

This is an issue in other languages also (for example ruby), you can check the discussion in
https://github.com/tonsky/FiraCode/issues/63
and the solution
https://github.com/atom/language-ruby/issues/117

It should have an easy fix, by adding something like the following before the operators match
{
    'match': '->|=>'
    'name': 'keyword.operator.rust'
 }

Not sure though if this is the best way to address the issue

**Comment by Victorystick** [comment]
This should be fixed by #59.

**Comment by siganos** [comment]
You are correct, it is basically the same issue.
