### ISSUE TITLE
Rust's `impl` are not highlighted quite correctly.

### ISSUE THREAD

**Issue by atheriel** [zargony/atom-language-rust#7]
I noticed this earlier today, but my regex skills are not up to solving it on my own:

![screen shot 2014-07-24 at 9 28 09 pm](https://cloud.githubusercontent.com/assets/1448326/3697917/54820cba-13b4-11e4-8715-e4f58514a0c8.png)

For the first `impl`, the type should be identified (as it is when following `struct`). For the second, both type (MyObject) and trait (Clone) should be identified, and "for" should not be confused as the control structure keyword `for`.

**Comment by zargony** [comment]
You're right. This is because the rule that matches impl statements is pretty basic right now. It's hard to match all cases because of the generic parameters. I tried a few times but didn't find a good solution either yet.
