### ISSUE TITLE
Snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [zargony/atom-language-rust#75]
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/darookee/vim-snippets/blob/master/UltiSnips/rust.snippets
https://github.com/rust-lang/sublime-rust/tree/master/snippets

Maybe you can add the missing snippets from other editors and implement it in your project.

**Comment by zargony** [comment]
Covered by #74
