### ISSUE TITLE
Rust new error format

### ISSUE THREAD

**Issue by jonathandturner** [zargony/atom-language-rust#80]
I'm not sure if this has any impact on this plugin, but just in case - we're currently discussing making the [switch to the new error format](https://github.com/rust-lang/rust/pull/35401).  If you're parsing the errors for the user, this may impact you.

This change will also enable a json mode, if you want something more structured to parse.

**Comment by jonathandturner** [comment]
Friendly reminder - we're now 17 days away from the 1.12 release, which will use the new error format and the stable json mode.

**Comment by zargony** [comment]
Thanks for the reminder :). This is about the new error format of the compiler output, right? So as long as there are no syntax changes to the language, we don't need to change anything (this package parses language syntax only and does not look at compiler output)

I'm looking forward to the new error output :smile:

**Comment by jonathandturner** [comment]
@zargony - sounds good.  and yup, no syntax changes (that I know of :))
