### ISSUE TITLE
apm install language-rust fails

### ISSUE THREAD

**Issue by FlyingPhil** [zargony/atom-language-rust#85]
The following error message is returned: 
Unable to download https://www.atom.io/api/packages/language-rust/versions/0.4.7/tarball: 404

I tried to install the package from the terminal and atom itself. Both fail.

**Comment by FFX01** [comment]
I'm having the same issues. Also tried both on the CLI and through the GUI. Ubuntu 14.04 LTS.

**Comment by zargony** [comment]
Sorry! I think I messed up the latest version tag and accidentally published the wrong one yesterday 😢 . Should be working with 0.4.8 now..

**Comment by FFX01** [comment]
Thanks for the quick fix!
