### ISSUE TITLE
Deprecated selector in `language-rust/styles/rust.less`

### ISSUE THREAD

**Issue by lexicalunit** [zargony/atom-language-rust#87]
In `language-rust/styles/rust.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .meta.attribute.rust` => `atom-text-editor.editor .syntax--meta.syntax--attribute.syntax--rust`

* `atom-text-editor::shadow .storage.modifier.lifetime.rust,
atom-text-editor::shadow .entity.name.lifetime.rust` => `atom-text-editor.editor .syntax--storage.syntax--modifier.syntax--lifetime.syntax--rust,
atom-text-editor.editor .syntax--entity.syntax--name.syntax--lifetime.syntax--rust`

* `atom-text-editor::shadow .keyword.unsafe.rust` => `atom-text-editor.editor .syntax--keyword.syntax--unsafe.syntax--rust`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by rumpelsepp** [comment]
When will this be released?

**Comment by zargony** [comment]
Just published a new version.

Sorry for the delay. Unfortunately, I don't get much free time for stuff like this plugin lately. If anybody likes to help out maintaining this little project, feel free to get in touch with me.
