### ISSUE TITLE
Highlight unused reserved words 

### ISSUE THREAD

**Issue by tinaun** [zargony/atom-language-rust#94]
it would be nice if there was a "warning" highlight for words that are still reserved, but have been never used or been removed from the language

the current list:
```
abstract
alignof
become
do
final
macro
offsetof
override
priv
proc
pure
sizeof
typeof
virtual
yield
```

**Comment by zargony** [comment]
Nice idea. We could scope them with something like `invalid.deprecated.rust`, which should display them in red in most color schemes.
